exclusions = []

additions = [
    # Crates that the compiler recommends
    # rg 'https://crates.io/crates/[a-z_-]+' --glob '*.stderr' --only-matching --no-line-number --no-filename | sort | uniq | cut -d '/' -f 5
    "async-trait",
    "async-recursion",
    "ethers",
    "ethers-solc",
    "pretty_assertions",
    "tokio",
    "parking_lot",
    "futures",
    "foundry-evm",
    "anvil",
    "anvil-core",
    "anvil-rpc",
    "anvil-server",
    "foundry-utils",
    "foundry-common",
    "forge",
    "foundry-config"
]
